FROM php:8.2-fpm

WORKDIR /var/www

RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
RUN ["sh",  "./nodesource_setup.sh"]

RUN apt-get update \
	# gd
	&& apt-get install -y \
	build-essential \
	openssl \
	libfreetype6-dev \
	libjpeg-dev \
	libpng-dev \
	libwebp-dev \
	zlib1g-dev \
	libzip-dev \
	gcc \
	g++ \
	make \
	vim \
	unzip \
	curl \
	git \
	jpegoptim \
	optipng \
	pngquant \
	gifsicle \
	locales \
	libonig-dev \
	nodejs \
	nginx \
	&& docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg \
	&& docker-php-ext-install gd \
	# gmp
	&& apt-get install -y --no-install-recommends libgmp-dev \
	&& docker-php-ext-install gmp \
	# pdo_mysql
	&& docker-php-ext-install pdo_mysql mbstring \
	# pdo
	&& docker-php-ext-install pdo \
	# mysqli
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-enable mysqli \
	# opcache
	&& docker-php-ext-enable opcache \
	# exif
    && docker-php-ext-install exif \
    && docker-php-ext-install sockets \
    && docker-php-ext-install pcntl \
    && docker-php-ext-install bcmath \
	# zip
	&& docker-php-ext-install zip \
	&& apt-get autoclean -y \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/pear/

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer

#COPY ../php-fpm-8-2-nginx-nodejs/build.dev.sh /var/www
COPY build.dev.sh /var/www

RUN chmod +x build.dev.sh

RUN chmod +rwx /var/www

RUN chmod -R 777 /var/www

# RUN usermod -u 1000 www-data

USER root

EXPOSE 80

CMD [ "sh", "./build.dev.sh" ]